"""What we sent, and how a reply finds its way back to the right invoice.

Two independent handles, because each fails in a different way and neither
fails in the other's.

The Message-ID is the standards answer: a reply carries In-Reply-To and
References naming the message it answers. It survived a real round trip
through Exchange. What it cannot survive is a mail system that rewrites the
Message-ID on the way out, and Gmail's SMTP is entitled to do exactly that
with a client-supplied one.

The token is the fallback: a random string in the reply address, which the
vendor's client copies back into To because that is what replying means. It
is generated by secrets, not derived from the invoice, so knowing an invoice
number buys nothing — which is the property the subject line does not have.

The subject line is deliberately not a third handle. It is free text chosen
by whoever writes it, and matching on it would mean anyone who learns an
invoice number can inject a vendor's answer. That is also why this registry
never looks at the body.

Session state, held in memory. A restart forgets what is outstanding, which
for a demo is right and for a deployment would be a table.
"""

import re
import secrets
from dataclasses import dataclass
from datetime import datetime

from apagent.schemas import InboundMail

# ap+INV-V005-3005.9tK2mQ7x@host — the invoice for a human reading a log, the
# token for the actual check.
_TOKEN_RE = re.compile(r"\+([A-Za-z0-9-]+)\.([A-Za-z0-9_-]{8,})@")


@dataclass
class SentQuery:
    """One outbound query, and everything needed to recognise its answer."""

    invoice_id: str
    message_id: str
    token: str
    reply_to: str
    sent_at: str
    chased_at: str | None = None
    escalated: bool = False
    answered: bool = False


class ThreadRegistry:
    """Outstanding vendor queries, keyed every way a reply might arrive."""

    def __init__(self) -> None:
        self._by_invoice: dict[str, SentQuery] = {}
        self._by_message_id: dict[str, SentQuery] = {}
        self._by_token: dict[str, SentQuery] = {}

    def register(self, invoice_id: str, mail_from: str) -> SentQuery:
        """Mint the Message-ID and token for a query about to be sent."""
        token = secrets.token_urlsafe(9)
        local, _, domain = mail_from.partition("@")
        message_id = f"<{secrets.token_hex(12)}.{invoice_id}@{domain or 'localhost'}>"
        query = SentQuery(
            invoice_id=invoice_id,
            message_id=message_id,
            token=token,
            reply_to=f"{local}+{invoice_id}.{token}@{domain}",
            sent_at=datetime.now().isoformat(timespec="seconds"),
        )
        self._by_invoice[invoice_id] = query
        self._by_message_id[message_id] = query
        self._by_token[token] = query
        return query

    def outstanding(self) -> list[SentQuery]:
        return [q for q in self._by_invoice.values() if not q.answered]

    def for_invoice(self, invoice_id: str) -> SentQuery | None:
        return self._by_invoice.get(invoice_id)

    def correlate(self, mail: InboundMail) -> tuple[str, str] | None:
        """(invoice_id, how) for a reply, or None if nothing ties it to us."""
        for header in [mail.in_reply_to, *reversed(mail.references)]:
            if header and header.strip() in self._by_message_id:
                return self._by_message_id[header.strip()].invoice_id, "in_reply_to"
        for address in mail.to_addrs:
            found = _TOKEN_RE.search(address)
            if found and found.group(2) in self._by_token:
                return self._by_token[found.group(2)].invoice_id, "token"
        return None
